---
- name: Create users
  hosts: dev
  gather_facts: false
  become: true
  tasks:
  - name: Ensure user exists
    vars:
      my_password: "{{ lookup('password', 'credentials/' + item + ' length=6')}}"
    loop: "{{ query('lines','cat users.txt') }}"
    user:
      name: "{{ item }}"
      state: "{{ my_state | default('present') }}"
      password: "{{ my_password | password_hash('sha512') }}"
      update_password: on_create
...
