---
- name: Create users
  hosts: dev
  become: true
  gather_facts: false
  vars:
    my_users:
      - fred
      - wilma
  tasks:
    - name: user is present
      user:
        name: "{{ item }}"
        state: "{{ my_state | default('present') }}"
        password: "{{ my_password | default('redhat') | password_hash('sha512') }}"
        update_password: on_create
      loop: "{{ my_users }}"
...
