---
- name: Using the password_hash filter
  hosts: dev
  gather_facts: false
  become: true
  tasks:
    - name: Ensure user exists
      user:
        name: "{{ my_user | default('lenovo') }}"
        password: "{{ my_password | default('redhat') | password_hash('sha512') }}"
        groups: wheel
        state: "{{ my_state | default('present') }}"
        update_password: on_create
