---
- name: Using uppercase filter
  hosts: dev
  gather_facts: true
  become: false
  tasks:
    - name: The variable my_var is shown in UPPERCASE
      debug:
        msg: "The value of my_var is {{ my_var | default('ansible') | upper }}"
...
